version: 2.1 # Use version 2.1 to enable Orb usage.

orbs:
  win: circleci/windows@5.0 # The Windows orb gives you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows virtual machine environment
      - add_ssh_keys:
          fingerprints:
            - "SHA256:pedvkYVGxQ2xSxeINVyTbOvQPaTHidyI309H0I2N99s"
      - checkout
      - run: Write-Host 'Hello, Windows'
