version: 2.1

jobs:
  build:
    docker:
      - image: circleci/gcc:latest  # or another image with the required tools
    steps:
      - checkout
      - run:
          name: Install CMake
          command: sudo apt-get update && sudo apt-get install cmake
      - run:
          name: Create Build Directory
          command: mkdir build
      - run:
          name: Run CMake
          command: cmake -Bbuild -H.  # Configure the project
      - run:
          name: Build
          command: cmake --build build  # Build the project

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
