version: 2.1 # Use version 2.1 to enable Orb usage.

orbs:
  win: circleci/windows@5.0 # The Windows orb gives you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor: win/default # executor type

    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:pedvkYVGxQ2xSxeINVyTbOvQPaTHidyI309H0I2N99s"
      - checkout
      - run:
          name: Install CMake
          command: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
      - run:
          name: Update Environment Variables
          command: Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"; Update-SessionEnvironment
      - run:
          name: Verify CMake Installation
          command: cmake --version
      - run:
          name: Create Build Directory
          command: New-Item -Path . -Name build -ItemType "directory"
      - run:
          name: Run CMake
          command: cmake -Bbuild -H.
      - run:
          name: Build
          command: cmake --build build

workflows:
  version: 2
  build_all:
    jobs:
      - build
